Update patch set 1
Patch Set 1:

After this is merged I anticipate the bump failing with something like: 

Exception: FileExistsError: [Errno 17] File exists:......

The bump will want to go in with: 
https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/38564

Patch-set: 1