add Enabled properties and remove unused methods nmiEnable
Currently, x86-power-control is using property "Enabled"
to monitor NMI Source. But, NMISource.interface.yaml didn't
have this "Enabled" property and the methods "nmiEnable" seems
unused in current openbmc design, remove it avoid usage confusion.

BTW, without this property "Enabled" then there was build error.
"error: class sdbusplus::xyz::openbmc_project::Chassis::Control::server
::NMISource has no member named 'enabled'"

Signed-off-by: Tim Lee <timlee660101@gmail.com>
Change-Id: I1d7751cfe0de6c919ecd0deaea4a801db4d8b86e